name: truecaller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  auto_route: ^9.3.0+1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  mobx: ^2.5.0
  shared_preferences: ^2.4.0
  telecom_manager:
    path: plugins/telecom_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.7.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
